//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class ModuleStudyAction : INotifyPropertyChanged
    {
        private int _id;
        private int _hours;
        private string _year;
    
    
        public virtual StudyActions StudyActions { get; set; }
        public virtual Module Module { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Group Group { get; set; }

        public int Id
        {
            get
            {
                return _id;
            }

            set
            {
                _id = value;
                RaisePropertyChangedEvent("Id");
            }
        }

        public int Hours
        {
            get
            {
                return _hours;
            }

            set
            {
                _hours = value;
                RaisePropertyChangedEvent("Hours");
            }
        }

        public string Year
        {
            get
            {
                return _year;
               
            }

            set
            {
                _year = value;
                RaisePropertyChangedEvent("Year");
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void RaisePropertyChangedEvent(string propertyName)

        {
            var handler = PropertyChanged;
            if (handler != null)
            {
                handler(this, new PropertyChangedEventArgs(propertyName));
            }
        }

    }
}
