//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }
        public string Semester { get; set; }
        public string Credits { get; set;}
        public Nullable<int> Lections { get; set; }
        public string Practices { get; set; }
        public string Labs { get; set; }
        public string Self { get; set; }
        public string Exam { get; set; }
        public string ZALIK { get; set; }
        public string Module_tests { get; set; }
        public string Course_work { get; set; }
        public string RGR { get; set; }
        public string DKR { get; set; }
        public string Referat { get; set; }
    
        public virtual StudyCycle StudyCycle { get; set; }
    }
}
