//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.ModuleStudyActions = new HashSet<ModuleStudyAction>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }
        public string Semester { get; set; }
        public double Credits { get; set; }
        public Nullable<int> Lections { get; set; }
        public Nullable<int> Practices { get; set; }
        public Nullable<int> Labs { get; set; }
        public Nullable<int> Self { get; set; }
        public Nullable<int> Exam { get; set; }
        public string ZALIK { get; set; }
        public Nullable<int> Module_tests { get; set; }
        public Nullable<int> Course_work { get; set; }
        public Nullable<int> Course_project { get; set; }
        public Nullable<int> RGR { get; set; }
        public Nullable<int> DKR { get; set; }
        public Nullable<int> Referat { get; set; }
    
        public virtual StudyCycle StudyCycle { get; set; }
        public virtual ICollection<ModuleStudyAction> ModuleStudyActions { get; set; }
    }
}
