//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeachersModelContainer : DbContext
    {
        public TeachersModelContainer()
            : base("name=TeachersModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<StudyCycle> StudyCycleSet { get; set; }
        public DbSet<Department> DepartmentSet { get; set; }
        public DbSet<Faculty> FacultySet { get; set; }
        public DbSet<Group> GroupSet { get; set; }
        public DbSet<StudyAction> StudyActionSet { get; set; }
        public DbSet<Module> ModuleSet { get; set; }
        public DbSet<ModuleStudyAction> ModuleStudyActionSet { get; set; }
        public DbSet<Teacher> TeacherSet { get; set; }
        public DbSet<Norm> NormSet { get; set; }
        public DbSet<Formula> FormulaSet { get; set; }
        public DbSet<TeacherWorkload> TeacherWorkloadSet { get; set; }
    }
}
